trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      pip install -r requirements.txt
      pytest
      python setup.py sdist bdist_wheel
    displayName: 'Build Python Application'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)/dist'
      artifactName: 'drop'
      publishLocation: 'Container'

- job: Deploy
  displayName: 'Deploy Job'
  dependsOn: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: AzureCLI@2
    displayName: 'Azure Login'
    inputs:
      azureSubscription:  'Pay-As-You-Go (23af9f78-f334-4099-8d16-d44d4c978994)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az login'

  - task: AzureCLI@2
    displayName: 'Copy Files to Azure Storage'
    inputs:
      azureSubscription:  'Pay-As-You-Go (23af9f78-f334-4099-8d16-d44d4c978994)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az storage blob upload-batch --account-name storageaccountmore --destination container --source $(Build.SourcesDirectory)/dist'

# Add more deployment steps or tasks as needed
