trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Install dependencies, run tests, package your Python application
    # Example commands:
      python --version  # Verify Python installation
      pip install --upgrade pip
      pip freeze > requirements.txt
      pip install -r requirements.txt
  displayName: 'Build Python Application'

- task: AzureCLI@2
  displayName: 'Azure Login'
  inputs:
    azureSubscription: 'Pay-As-You-Go (23af9f78-f334-4099-8d16-d44d4c978994)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az login'

- task: AzureCLI@2
  displayName: 'Copy Files to Azure Storage'
  inputs:
    azureSubscription: 'Pay-As-You-Go (23af9f78-f334-4099-8d16-d44d4c978994)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload-batch --account-name storageaccountmore --destination content --source ./dist'



